- name: Disable default nginx module
  ansible.builtin.shell: dnf module disable nginx -y


- name: Enable Nginx 24 Version
  ansible.builtin.shell: dnf module enable nginx:1.24 -y

- name: Install Nginx
  ansible.builtin.dnf:
    name: nginx
    state: latest

- name: Copy nginx config file
  ansible.builtin.template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Setup app prerequsities
  ansible.builtin.include_role:
    name: common
    tasks_from: app-prerequites
#APP_PREREQ

- name: Start Nginx Service
  ansible.builtin.systemd:
    state: restarted
    name: nginx
    enabled: true